name: lang-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - pytest
  - requests
  - sqlalchemy
  - toolz
  - pip
  - pip:
      - beautifulsoup4
      - bs4
      - flask
      - flask-cors
      - openai~=1.60.1
      - sqlalchemy-utils
      - python-dotenv
      - psycopg2
      - langchain==0.1.14
      - langchain-core==0.1.37
      - langchain-openai==0.0.8
      - langchain-community==0.0.31
      - langchain-text-splitters==0.0.2
      - langsmith==0.1.147

pytest~=8.3.4
flask~=3.1.0
flask-cors~=5.0.0
openai~=1.60.1
sqlalchemy~=2.0.37
toolz~=1.0.0
psycopg2~=2.9.10
sqlalchemy-utils~=0.41.2
requests~=2.32.3
bs4~=0.0.2
beautifulsoup4~=4.12.3
numpy~=2.2.2
pandas~=2.2.3
python-dotenv~=1.0.1
soupsieve~=2.6
h11~=0.14.0
ipython~=8.32.0
pip~=24.3.1
attrs~=25.1.0
distro~=1.9.0
pysocks~=1.7.1
openssl~=3.4.0
pyzmq~=26.2.1
colorama~=0.4.6
pexpect~=4.9.0
tornado~=6.4.2
cffi~=1.17.1
comm~=0.2.2
traitlets~=5.14.3
h2~=4.1.0
importlib-metadata~=8.6.1
psutil~=6.1.1
typing_extensions~=4.12.2
nest-asyncio~=1.6.0
werkzeug~=3.1.3
ipykernel~=6.29.5
yaml~=0.2.5
pyyaml~=6.0.2
parso~=0.8.4
jedi~=0.19.2
mypy-extensions~=1.0.0
pytz~=2024.1
idna~=3.10
multidict~=6.1.0
propcache~=0.2.1
sniffio~=1.3.1
markupsafe~=3.0.2
click~=8.1.8
jinja2~=3.1.5
blinker~=1.9.0
itsdangerous~=2.2.0
httpcore~=1.0.7
pygments~=2.19.1
zstandard~=0.23.0
certifi~=2024.12.14
jiter~=0.8.2
charset-normalizer~=3.4.1
six~=1.17.0
regex~=2024.11.6
platformdirs~=4.3.6
httpx~=0.28.1
pydantic~=2.10.6
anyio~=4.8.0
orjson~=3.10.15
python-dateutil~=2.9.0.post0
tenacity~=9.0.0
packaging~=24.2
wcwidth~=0.2.13
pluggy~=1.5.0
exceptiongroup~=1.2.2
iniconfig~=2.0.0
yarl~=1.18.3
aiohttp~=3.11.11
aiosignal~=1.3.2
frozenlist~=1.5.0
aiohappyeyeballs~=2.4.4
debugpy~=1.8.12
greenlet~=3.1.1
decorator~=5.1.1
stack_data~=0.6.3
matplotlib-inline~=0.1.7
pickleshare~=0.7.5
jupyter_client~=8.6.3
prompt-toolkit~=3.0.50
ptyprocess~=0.7.0
jupyter_core~=5.7.2
annotated-types~=0.7.0
urllib3~=2.3.0
tiktoken~=0.8.0
asttokens~=3.0.0
executing~=2.1.0
langchain-core~=0.3.31
langchain~=0.3.17
langchain-community~=0.3.16
langsmith~=0.3.1
langchain-text-splitters~=0.3.5
async-timeout~=4.0.3
requests-toolbelt~=1.0.0
pure_eval~=0.2.3
pycparser~=2.22
jsonpointer~=3.0.0
zipp~=3.21.0
python~=3.13.1
jsonpatch~=1.33
langchain-openai~=0.3.2