name: lang-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - pytest
  - requests
  - sqlalchemy
  - toolz
  - pip
  - pip:
      - beautifulsoup4
      - bs4
      - flask
      - flask-cors
      - openai
      - langchain-openai
      - langchain_community
      - sqlalchemy-utils
      - python-dotenv
      - psycopg2
